### ISSUE TITLE
node example.js fails on Error

### ISSUE THREAD

**Issue by ghost** [stephenhandley/type-of-is#7]
Error function fail in node

C:\Temp\generate-schema\node_modules\type-of-is>node --version
v6.9.4

C:\Temp\generate-schema\node_modules\type-of-is>node example.js
[Function: String]
[Function: Number]
[Function: Object]
[Function: Array]
null
undefined
[Function: Boolean]
[Function: Function]
[Function: RegExp]
[Function: Date]
**{ [Function: Error]
captureStackTrace: [Function: captureStackTrace],
stackTraceLimit: 10 }**
String
Number
Object
Array
null
undefined
Boolean
Function
RegExp
Date
Error
true
false
true
true
false
false
true
true
true
false
true
false
[Function: Person]
true
false
true
true
[Function: Object]
[Function: Number]
[Function: Number]
[Function: Number]
[Function: Object]
[Function: Object]
T
true
false

**Comment by stephenhandley** [comment]
I think errors just get printed differently in node now

```
> console.log(Error);
{ [Function: Error] stackTraceLimit: 10 }
```

```
> require('type-of-is').is(new Error('omg'), Error)
true
```

**Comment by mncourt** [comment]
Ahhh ok.  Thanks.
